# Generated by Django 4.2.7 on 2023-11-12 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contacts', '0003_spamphonenumbers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='spamPhoneNumbers',
            new_name='spamPhoneNumber',
        ),
    ]
